Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

IfUnlessModifier:
  Enabled: false
