require:
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-factory_bot
  - rubocop-rails

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Style/IfUnlessModifier:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicateMethod:
  Enabled: false

# RSpec-specific configuration
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# Capybara cops causing errors - disable for now
Capybara/RSpec/PredicateMatcher:
  Enabled: false
