plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-rails

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Style/IfUnlessModifier:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ModuleLength:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# RSpec-specific configuration
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 35

RSpec/DescribeClass:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4

Metrics/ClassLength:
  Exclude:
    - "spec/integration/test_server_generator.rb"

# Capybara cops causing errors - disable for now
RSpec/PredicateMatcher:
  Enabled: false
