Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Style/IfUnlessModifier:
  Enabled: false

AllCops:
  NewCops: enable
